### ISSUE TITLE
An invitation to PixivUWP project

### ISSUE THREAD

**Issue by ThomasWFan** [cucmberium/Pixeez#1]
Respectful cucmberium,
  I find it impossible to contact you directly on Github, so sorry for my creating the issue trying to contact you. I am a Chinese developer, and I am now trying to develop a UWP app that can provide the same experience as the Android app for Pixiv. After reading your code, I and other developers of the PixivUWP project decided to invite you to our project. If you are interested in it, you can contact thomasw.fan@outlook.com. I will tell you more details with this Email.

Sincerely,
ThomasWFan

**Comment by cucmberium** [comment]
I used to make UWP Pixiv client called Pixitle. (Pixitle can be downloaded from the following URL. https://www.microsoft.com/ja-jp/store/p/pixitle/9nblggh4mxl4) However, it is not maintained for a long time and it can not be used properly. That's because I am busy. So I can not join the PixivUWP project.

If you need support, I would like to help with that. (Eg translation of your app or improvement of Pixeez etc) If you need source code of Pixitle, I will publish it to github. In that case, please contact `coppermine＠clarkdale.sakura.ne.jp`.

Best regards,
cucmberium

**Comment by ThomasWFan** [comment]
Thanks for your reply.
